### PR TITLE
Use deterministic unique ids in Descriptions

### LINKED ISSUE #1120: Unable to use surefire maven plugin to rerun failing tests
## Summary

Using [surefire to rerun failing tests ](https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html) results in a stack trace.

- cucumber-java8:1.2.5
- maven-failsafe-plugin:2.20
- maven-surefire-plugin:2.20 

## Expected Behavior

When using surefire with `mvn -Dfailsafe.rerunFailingTestsCount=2 test` I expect the failing tests to be rerun.

## Current Behavior

```
org.apache.maven.surefire.testset.TestSetFailedException: Unable to create test class 'Scenario: Fail when running'
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeFailedMethod(JUnit4Provider.java:385)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:292)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
Caused by: java.lang.ClassNotFoundException: Scenario: Fail when running
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeFailedMethod(JUnit4Provider.java:379)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:292)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
```

## Possible Solution

Surefire parses the test description for the class to rerun and expects a class name here rather then a human readable name. Either provide a class name or help convince the surefire folks to fix this this. :)

See: [SUREFIRE-1372](https://issues.apache.org/jira/browse/SUREFIRE-1372)

## Steps to Reproduce (for bugs)

1. Setup mvn project with a failing cucumber test
2. Add a test runner that uses `@RunWith(Cucumber.class)` and `@CucumberOptions(...)`
3. Run mvn -Dfailsafe.rerunFailingTestsCount=2 test
4. Observe stacktrace.

## Context & Motivation

Rerunning failing tests as an integral part of the build, especially in large tests  sets that are ran overnight, allows us to prioritize investigating the genuine failures over the flaky ones.

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary

Improve surefire integration.

## Motivation and Context
 Rerunning failed tests with Surefire requires a method to identify the tests.
 Surefire currently uses a tuple of (Class, Method) to identify failed tests.
 Cucumber-jvm uses test suites which do not consist of Classes or methods.
 Therefore another method is needed.

 JUnit provides the option to select tests that match a Description.
 Descriptions are compared using  a unique Id. To identify tests between
 different runs we should provide Descriptions with a predictable unique
 id.

 The current implementation did not suffice. While the provided cucumber
 elements are unique, they are not predictable between runs making it
 impossible to use their descriptions to rerun a failed test.

 After this change it will be possible to update Surefire to use
 descriptions to rerun failed tests.

  Related Issues:
  - https://issues.apache.org/jira/browse/SUREFIRE-1372
  - https://github.com/cucumber/cucumber-jvm/issues/1120
  - https://github.com/temyers/cucumber-jvm-parallel-plugin/issues/31

Closes #1120.

## How Has This Been Tested?

Replaced `ExecutionUnitRunnerTest#shouldPopulateRunnerStepsWithStepsUsedInStepDescriptions` with `FeatureRunnerTest#shouldPopulateDescriptionsWithStableUniqueIds` that creates the same feature twice and tests the id's are unique and predictable.

The reproducer for Surefire can be found [in my fork of Surefire](
https://github.com/mpkorstanje/maven-surefire/tree/SUREFIRE-1372/surefire-integration-tests/src/test/resources/junit47-rerun-failing-tests-with-cucumber). Running with cucumber 1.2.5 results in failed tests, with the result of this PR as 2.0.0-SNAPSHOT results in 2 flakes. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).

## Checklist:
- [X] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: junit/src/main/java/cucumber/runtime/junit/PickleRunners.java [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+    }
+
+
+    static PickleRunner withNoStepDescriptions(cucumber.runner.Runner runner, PickleEvent pickleEvent, JUnitReporter jUnitReporter) throws InitializationError {
+        return new NoStepDescriptions(runner, pickleEvent, jUnitReporter);
+    }
+
+
+    static class WithStepDescriptions extends ParentRunner<PickleStep> implements PickleRunner {
+        private final Runner runner;
```
Comment (mpkorstanje) [inline junit/src/main/java/cucumber/runtime/junit/PickleRunners.java]: The reason for two separate classes is because the semantics of ParentRunner somewhat expect there to be children. It can be hacked but doing so would make things fragile.

File: junit/src/test/java/cucumber/runtime/junit/CucumberTest.java [hunk 2]
```diff
@@ -42,14 +42,14 @@ public void ensureOriginalDirectory() {
     @Test
     public void finds_features_based_on_implicit_package() throws IOException, InitializationError {
         Cucumber cucumber = new Cucumber(ImplicitFeatureAndGluePath.class);
-        assertEquals(3, cucumber.getChildren().size());
+        assertEquals(2, cucumber.getChildren().size());
         assertEquals("Feature: FA", cucumber.getChildren().get(0).getName());
```
Comment (mpkorstanje) [inline junit/src/test/java/cucumber/runtime/junit/CucumberTest.java]: Because I inlined feature_with_same_steps_in_different_scenarios.feature

File: junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java [hunk 3]
```diff
@@ -93,22 +93,69 @@ protected void runChild(PickleStep step, RunNotifier notifier) {
...
-    private PickleStep step;
+    private static final class PickleStepId implements Serializable {
+        private static final long serialVersionUID = 1L;
+        private final String uri;
+        private final int pickleLine;
+        private final int pickleStepLine;
 
-    PickleStepWrapper(PickleStep step) {
-        this.step = step;
+        PickleStepId(PickleEvent pickleEvent, PickleStep pickleStepLine) {
```
Comment (brasmusson) [inline junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java]: I assume it should be `pickleStep` instead of `pickleStepLine`, I fix that.

File: junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java [hunk 4]
```diff
@@ -89,17 +93,67 @@ public void should_call_formatter_for_scenario_outline_with_two_examples_table_a
...
+            "    | D    |\n" +
+            "    | E    |\n"
+
+        );
+
+        FeatureRunner runner = createFeatureRunner(cucumberFeature);
+        FeatureRunner rerunner = createFeatureRunner(cucumberFeature);
+
+        Set<Description> descriptions = new HashSet<Description>();
+        assertDescriptionIsUnique(runner.getDescription(), descriptions);
```
Comment (brasmusson) [inline junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java]: It is a bit unusual for an assert-method to modify its arguments, but checking the uniqueness with a set makes sence - and then the set has been create and can be used subsequently.

File: junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java [hunk 5]
```diff
@@ -89,17 +93,67 @@ public void should_call_formatter_for_scenario_outline_with_two_examples_table_a
...
-        FeatureRunner runner = new FeatureRunner(cucumberFeature, runtime, new JUnitReporter(runtime.getEventBus(), false, new JUnitOptions(Collections.<String>emptyList())));
-        RunNotifier notifier = mock(RunNotifier.class);
-        runner.run(notifier);
-        return notifier;
+        return new FeatureRunner(cucumberFeature, runtime, new JUnitReporter(runtime.getEventBus(), false, new JUnitOptions(Collections.<String>emptyList())));
+    }
+
+
+    @Test
+    public void shouldPopulateDescriptionsWithStableUniqueIds() throws Exception {
```
Comment (brasmusson) [inline junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java]: Most test method uses the non-idomatic form of using underscore, since some/many of us contributors find them easier to read (and in tests readability is even more important than elsewhere), see discussion at https://github.com/cucumber/cucumber-jvm/pull/302#issuecomment-5267175

File: junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java (hunk 3 above)
Comment (mpkorstanje) [inline junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java]: That is correct.
