### PR TITLE
[Spring] Throw when step definitions have the Component stereotype

### LINKED ISSUE #1225: [Spring] Exception is thrown complaining about multiple matching beans with version 1.2.5
In the process of transitioning from version Cucumber 1.1.8 to 1.2.5 I have ran into an issue where the below exception is thrown:

`CucumberException No qualifying bean of type x is defined: expected single matching bean but found 2`

I tried to dig a bit deeper and I see that the `<T> T getInstance(final Class<T> type)` method in `SpringFactory` class had changed and apparently is somehow responsible for that behavior.

I was able to replicate this behavior in a simple project which I uploaded to github and the link is below.

Cucumber Version: 1.2.5
Operating System and version: Windows 7
Link to your project: https://github.com/EugeneS30/cucumber-bean-defect-verification.git

### PR DESCRIPTION
**Pull request by mpkorstanje**
When step definitions are annotated with `@Component` or other related
annotations they can be picked up by springs class path scanning. This
conflicts with cucumbers class path scanning and may result in
multiple bean definitions for the same class.

This problem is hard to understand and hard to trace. By making the
problem explicit and providing a clear instruction on how to resolve
this we can hopefully avoid future confusion.

The current implementation only checks the a subset of all annotations.
This will hopefully be sufficient.

Closes #1225

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [X] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java [hunk 1]
```diff
@@ -73,6 +87,20 @@ public boolean addClass(final Class<?> stepClass) {
         return true;
     }
 
+    private void checkNoComponentAnnotations(Class<?> type) {
```
Comment (mpkorstanje) [inline spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java]: This is not going to work. This should recursively search the annotations annotations for `@Component` taking care not to get stuck in a loop.

File: gosu/pom.xml [hunk 2]
```diff
@@ -53,10 +53,5 @@
             <artifactId>junit</artifactId>
             <scope>test</scope>
         </dependency>
-        <dependency>
-            <groupId>org.mockito</groupId>
-            <artifactId>mockito-all</artifactId>
```
Comment (mpkorstanje) [inline gosu/pom.xml]: mockito-all packages an older version hamcrest which conflicts with the one provided by junit and should not be used.
