### PR TITLE
 [Core, TestNg] Clean up stream closing

### LINKED ISSUE #1108: HtmlFormatter doesn't close Stream for embedded image.
## Summary

It looks like the HtmlFormatter forgets to close the FileOutputStream of an image being embedded.

## Expected Behavior

The HtmlFormatter should close all streams and there should be no log-error about a stream not being closed.

## Current Behavior

Although my tests pass, I get the following exception:
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                             java.lang.Throwable: Explicit termination method 'close' not called
                                                 at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                 at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
                                                 at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
                                                 at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:34)
                                                 at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:24)
                                                 at cucumber.runtime.formatter.HTMLFormatter.reportFileOutputStream(HTMLFormatter.java:229)
                                                 at cucumber.runtime.formatter.HTMLFormatter.embedding(HTMLFormatter.java:157)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at cucumber.runtime.Utils$1.call(Utils.java:40)
                                                 at cucumber.runtime.Timeout.timeout(Timeout.java:16)
                                                 at cucumber.runtime.Utils.invoke(Utils.java:34)
                                                 at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
                                                 at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                 at $Proxy6.embedding(Unknown Source)
                                                 at cucumber.runtime.ScenarioImpl.embed(ScenarioImpl.java:61)
                                                 ...
```

## Possible Solution

In HtmlFormatter there is a private method `writeBytesAndClose(byte[], OutputStream)`, which writes bytes, but does not close the stream as the method-name indicates. Closing the stream could possibly help.

## Context & Motivation

If not fixed, I'm scared of a memory-leak, when our test-suite grows.

## Your Environment

* Version used: cucumber-core:1.2.5
* Operating System and version: Windows 7
* I'm using cucumber to test an Android-app.

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Summary

  Refactored the code around streams so it follows these rules:
   - Streams should be closed by their owners
   - A stream is owned by its creator or when provided as a constructor argument
   - Stream ownership should be the smallest possible unit. The method, class, process, system.
   - System.out and System.error may never be closed

 Fixes #1108 

## How Has This Been Tested?

Checked the code for all occurrences of ` .close()`,`System.out`, `System.error`, `new NiceAppendable`, `new .*OutputStream` and `new .*Writer`in non-test code.

Automated tests should be passing. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: core/src/main/java/cucumber/api/formatter/NiceAppendable.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public NiceAppendable println(CharSequence csq) {
     public void close() {
         try {
             tryFlush();
-            if (out instanceof Closeable && out != System.out && out != System.err) {
+            if (out instanceof Closeable) {
```
Comment (mpkorstanje) [inline core/src/main/java/cucumber/api/formatter/NiceAppendable.java]: This is the responsibility of the caller who passes in System.out or System.error

File: core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java [hunk 2]
```diff
@@ -119,11 +120,11 @@ public void receive(TestRunFinished event) {
     };
 
     public HTMLFormatter(URL htmlReportDir) {
-        this.htmlReportDir = htmlReportDir;
+        this(htmlReportDir, createJsOut(htmlReportDir));
```
Comment (mpkorstanje) [inline core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java]: Idiomatic java.

File: core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java [hunk 3]
```diff
@@ -463,50 +464,69 @@ private void copyReportFiles() {
...
+        try {
+            return new URL(htmlReportDir, fileName);
+        } catch (IOException e) {
+           throw new CucumberException(e);
+        }
+    }
+
+    private static void writeStreamToURL(InputStream in, URL url) {
+        OutputStream out = createReportFileOutputStream(url);
+
```
Comment (mpkorstanje) [inline core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java]: Minimizess the ownership scope of the output stream

File: core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java [hunk 4]
```diff
@@ -463,50 +464,69 @@ private void copyReportFiles() {
...
             int len = in.read(buffer);
             while (len != -1) {
                 out.write(buffer, 0, len);
                 len = in.read(buffer);
             }
-            out.close();
         } catch (IOException e) {
             throw new CucumberException("Unable to write to report file item: ", e);
+        } finally {
+            closeQuietly(out);
```
Comment (mpkorstanje) [inline core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java]: Idiomatic java. For lack of being able to use try-with-resources

File: core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java [hunk 5]
```diff
@@ -463,50 +464,69 @@ private void copyReportFiles() {
...
         }
     }
 
-    private void writeBytesAndClose(byte[] buf, OutputStream out) {
+    private static void writeBytesToURL(byte[] buf, URL url) throws CucumberException {
+        OutputStream reportFileOutputStream = createReportFileOutputStream(url);
```
Comment (mpkorstanje) [inline core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java]: Minimizes the ownership scope of the output stream

File: core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java [hunk 6]
```diff
@@ -301,4 +304,12 @@ private Element createException(Document doc, String clazz, String message, Stri
...
         }
     }
+
+    private static void closeQuietly(Closeable out) {
+        try {
+            out.close();
+        } catch (IOException ignored) {
+            // go gentle into that good night
+        }
+    }
```
Comment (mpkorstanje) [inline core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java]: 3rd duplication but I'd rather wait for java7 try-with-resources

**Comment by brasmusson** [comment]
Yes, this looks like a better solution than the one I did in https://github.com/cucumber/cucumber-jvm/commit/51f0c9b3b890012334fdd1cfecbd6646b6bebdf2.
