### PR TITLE
[Core] Fix unfinished sentence in Javadoc

### LINKED ISSUE #2690: Unfinished sentence in Javadoc
### 👓 What did you see?

> Thought to point out an unfinished sentence here. It's [still present in `main`](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/options/Constants.java#L124).
> @timtebeek - https://github.com/cucumber/cucumber-jvm/commit/ad47dd5000c4d40151e99d35418ea58b76f41d2c#r98362078

### PR DESCRIPTION
**Pull request by vishesh10**
### 🤔 What's changed?

Fixed the incomplete sentence in Javadoc.

### ⚡️ What's your motivation? 

Fixes #2690

### 🏷️ What kind of change is this?

- :bank: Refactoring (improvement to documentation)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.

----

### CODE REVIEW

File: cucumber-core/src/main/java/io/cucumber/core/options/Constants.java [hunk 1]
```diff
@@ -134,7 +134,7 @@ public final class Constants {
     /**
      * Property name formerly used to pass command line options to Cucumber:
      * {@value} This property is no longer read by Cucumber. Please use any of
-     * the
+     * the individual·properties·instead.
```
Comment (mpkorstanje) [inline cucumber-core/src/main/java/io/cucumber/core/options/Constants.java:137]: There appear to be some dots here.

**Review by mpkorstanje — CHANGES_REQUESTED** [review]

**Comment by mpkorstanje** [comment]
Cheers. Looks good!
