### PR TITLE
Reduce duplication between code and snippet generation

### LINKED ISSUE #3063: Reduce duplication between code and snippet generation
### 🤔 What's the problem you've observed?

Currently boths `GenerateI18n` classes for `cucumber-java[8]` and `SnippetGenerator` turn Gherkin keywords into code.  This code is now duplicated 3 times over. Each with a special exception for Emoji.

### ✨ Do you have a proposal for making it better?

Extract and reuse this code.

### 📚 Any additional context?

_No response_

### PR DESCRIPTION
**Pull request by ielatif**
Fixes #3063

### ⚡️ What's your motivation? 

As seen in https://github.com/cucumber/cucumber-jvm/pull/3062 currently boths GenerateI18n classes for cucumber-java[8] and SnippetGenerator turn Gherkin keywords into code. This code is now duplicated 3 times over. Each with a special exception for Emoji.

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)

### CODE REVIEW

File: cucumber-core/src/main/java/io/cucumber/core/codegen/GherkinKeywordNormalizer.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
+package io.cucumber.core.codegen;
```
Comment (ielatif) [inline cucumber-core/src/main/java/io/cucumber/core/codegen/GherkinKeywordNormalizer.java]: Introduced new package `io.cucumber.core.codegen`

**Comment by ielatif** [comment]
Build fail with error : 

[ERROR] java.class.externalClassExposedInAPI: class io.cucumber.gherkin.GherkinDialect: A class from supplementary archives is used in a public capacity in the API. [io.cucumber:gherkin:jar:36.1.0]

@mpkorstanje  can you advice in which module should i put GherkinKeywordNormalizer class ?
