### PR TITLE
Run a seperate TestNG test per scenario

### LINKED ISSUE #1113: Running cucumber scenarios using TestNG (Scenario level)
## Summary
When we run the  Cucumber-jvm using TestNG, by default it runs each and every feature file as a single Test case. What I want is basically it should give functionality to run each and every scenario with examples as single test case.

## Expected Behavior
I want to create screenshots of the test failure and I am currently using selenium with cucumber-testng. Selenium listener is used to capture the event and based on the event it captures the screenshots. But this happens only on a feature level, not at the scenario level. 
My expectation is I want each scenario to be passed in @Test such that if any scenarios fails. It should trigger the event for test fail such that my code would capture the event.

## Current Behavior
It takes all the scenarios as a single test case. So my code is generating the screenshots if any scenarios fails in the feature and a single snap is generated for a particular feature file.
It runs the scenarios one after the other and doesn't trigger any event for the failure.

~~~
~~~

## Possible Solution
By extending the feature of 		```testNGCucumberRunner.runCucumber(cucumberFeature.getCucumberFeature()); ```
such as 
```testNGCucumberRunner.runCucumberScenario(cucumberFeature.getFeatureScenario(scenarioname))```

## Steps to Reproduce (for bugs)

1. Functionality for getting all scenarios name and examples
2. Adding a method for running cucumber scenario by passing every scenario name
3. Throw exception if the scenario name is not present
4. Run every scenario as a @Test kind 

## Context & Motivation
This will help in achieving the scenario level runtime options for the QA for handling events such as creating screenshots or onSuccess things to be done.
Feature level Test helps in solving the issues on modular level. But Scenario level test will help in achieving the sub-functionalities and various other uses cases per module.

## Your Environment

* Operating System and version: Mac

### PR DESCRIPTION
**Pull request by lucianovdveekens**
## Summary

Currently, each feature runs as one test in TestNG. This PR changes that to one test for each scenario in a feature file.

Another PR #1118 already exists, but it's based on old libraries.

## Motivation and Context

Fixes #1113 & supersedes and closes #1118

## How Has This Been Tested?

I've updated existing unit tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: core/src/main/java/cucumber/runtime/Runtime.java [hunk 1]
```diff
@@ -121,6 +121,12 @@ public void runFeature(CucumberFeature feature) {
         }
     }
 
+    public void runPickle(PickleEvent pickle) {
```
Comment (brasmusson) [inline core/src/main/java/cucumber/runtime/Runtime.java]: There should be no `runPickle` on the `Runtime`, instead the `TestNGCucumberRunner` should do what for instance the [Android executor](https://github.com/cucumber/cucumber-jvm/blob/master/android/src/main/java/cucumber/runtime/android/CucumberExecutor.java#L113) and call `runPickle` on the `Runner`.

File: core/src/main/java/cucumber/runtime/Runtime.java [hunk 2]
```diff
@@ -121,6 +121,12 @@ public void runFeature(CucumberFeature feature) {
...
+        if (matchesFilters(pickle)) {
```
Comment (brasmusson) [inline core/src/main/java/cucumber/runtime/Runtime.java]: Already the data provider `provideScenarios` should filter the `PickleEvent`, otherwise it will look like they were run and passed, when in fact they were not selected for execution.

File: testng/src/main/java/cucumber/api/testng/CucumberFeatureWrapperImpl.java [hunk 3]
```diff
@@ -22,6 +22,6 @@ public CucumberFeature getCucumberFeature() {
 
     @Override
     public String toString() {
-        return cucumberFeature.getGherkinFeature().getFeature().getName();
+        return cucumberFeature.getPath();
```
Comment (brasmusson) [inline testng/src/main/java/cucumber/api/testng/CucumberFeatureWrapperImpl.java]: I think it still should be the feature name here (possibly surrounded by "") for the sake of consistency, we have tried to standardise on the feature name as the "classname" see #1167.

File: testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java [hunk 4]
```diff
@@ -58,7 +59,7 @@ public void runCukes() {
         }
     }
 
-    public void runCucumber(CucumberFeature cucumberFeature) {
+    public void runFeature(CucumberFeature cucumberFeature) {
```
Comment (brasmusson) [inline testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java]: Do not change this method name, it makes the PR contain breaking changes for those people that use the structure of the RunCukesByFeatureAndCompositionTest example runner in the java-calculator-testng example.

File: testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java [hunk 5]
```diff
@@ -68,6 +69,10 @@ public void runCucumber(CucumberFeature cucumberFeature) {
         }
     }
 
+    public void runScenario(PickleEvent pickle) throws Throwable {
+        runtime.runPickle(pickle);
```
Comment (brasmusson) [inline testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java]: Not using a listener as in `runCucumber` make Ambiguous and Undefined result to be missed (TestNG seems to detect exceptions from the step definitions, but not the exceptions for Ambiguous and Undefined result which are thrown internally in the runner). I'll provide a Listener class (similar to the `FeatureResultListener`) which I had to make to get to the bottom of this behaviour.

File: testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java [hunk 6]
```diff
@@ -97,4 +102,25 @@ public void finish() {
...
+    public Object[][] provideScenarios() {
+        try {
+            List<Object[]> scenarios = new ArrayList<Object[]>();
+
+            List<CucumberFeature> features = getFeatures();
+            for (CucumberFeature feature : features) {
+                List<PickleEvent> pickles = runtime.compileFeature(feature);
+
+                for (PickleEvent pickle : pickles) {
+                    scenarios.add(new Object[]{new PickleEventWrapper(pickle), new CucumberFeatureWrapperImpl(feature)});
```
Comment (brasmusson) [inline testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java]: It is here that `runtime.matchesFilters(pickle)` should be used to select the pickles to run.

File: testng/src/test/java/cucumber/api/testng/TestNGCucumberRunnerTest.java [hunk 7]
```diff
@@ -30,7 +30,7 @@ public void runCukesStrict() throws Exception {
     @Test
     public void parse_error_propagated_to_testng_test_execution() throws Exception {
         testNGCucumberRunner = new ParseErrorCucumberRunner(RunCukesTest.class);
-        Object[][] features = testNGCucumberRunner.provideFeatures(); // provideFeatures() throws CucumberException
+        Object[][] features = testNGCucumberRunner.provideScenarios(); // provideFeatures() throws CucumberException
```
Comment (brasmusson) [inline testng/src/test/java/cucumber/api/testng/TestNGCucumberRunnerTest.java]: Also the comment needs to updated.

File: testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java (hunk 5 above)
Comment (brasmusson) [inline testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java]: So I did succeed in pushing a commit onto your pull request branch with the result listener and the update of `runScenario`, very convenient.

Comment (lucianovdveekens) [inline testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java]: I totally missed that, thanks!

Comment (lucianovdveekens) [inline testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java]: I've added a test that verifies the working of the new listener when a scenario contains undefined steps and the 'strict' flag is set.
